/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JEventViewer */

#ifndef _Included_JEventViewer
#define _Included_JEventViewer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JEventViewer
 * Method:    displayEntries
 * Signature: (Ljava/util/Vector;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_JEventViewer_displayEntries
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
